apiVersion: v1
kind: Service
metadata:
  name: croc-hunter
  labels:
    app: croc-hunter
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    run: croc-hunter
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: croc-hunter
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: croc-hunter
        app: croc-hunter
    spec:
      containers:
      - name: croc-hunter
        image: karcontainers-microsoft.azurecr.io/samples/croc-hunter
        env:
        - name: HOST_PLATFORM
          value: "ACS Kubernetes"
        ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: "regsecret"
